/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Scanner;

public class App {

    public void escrever() {

        File arquivo = new File("saida.txt");

        try (FileWriter fileWriter = new FileWriter(arquivo);

                BufferedWriter bufferedw = new BufferedWriter(fileWriter);

        ) {

            bufferedw.write("Olá mundo\n");

        } catch (Exception e) {

            System.err.println("Deu erro: " + e);
        }
    }

    public void ler() {

        File arquivo = new File("saida.txt");

        try (Scanner leitor = new Scanner(arquivo)) {

            // while (leitor.hasNextLine()) {

            // System.out.println(leitor.nextLine());
            // }

            String linha = leitor.nextLine();

            String[] dispostivios = linha.split("--");

            System.out.printf("Origem %s -- Destino: %s\n", dispostivios[0], dispostivios[1]);

        } catch (Exception e) {
            System.err.println("Deu Erro: " + e);
        }

    }

    public void salvarPessoa(Pessoa p) {

        File arquivo = new File("contatos.txt");

        try (FileOutputStream fos = new FileOutputStream(arquivo, true);

                ObjectOutputStream oos = new ObjectOutputStream(fos);) {

            oos.writeObject(p);

        } catch (Exception e) {

            System.err.println("Deu erro: " + e);
        }
    }

    public Pessoa lerPessoa() {
        Pessoa p = null;
        File arquivo = new File("contatos.txt");

        try (FileInputStream fis = new FileInputStream(arquivo);

                ObjectInputStream ois = new ObjectInputStream(fis)) {

            p = (Pessoa) ois.readObject(); // codigo inseguro

        } catch (Exception e) {

            System.err.println("deu erro: " + e);
        }
        return p;
    }

    public static void main(String[] args) {

        // File arquivo;

        // try {

        // arquivo = new File("arquivo.txt");

        // FileWriter fwArquivo = null;

        // if (arquivo.exists() == true) {

        // fwArquivo = new FileWriter(arquivo, true);

        // } else {

        // fwArquivo = new FileWriter(arquivo);
        // }

        // BufferedWriter bw = new BufferedWriter(fwArquivo);

        // bw.close();
        // fwArquivo.close();

        // } catch (Exception e) {

        // }

        App app = new App();

        // Pessoa p = new Pessoa("Arthur", "12973123123");

        System.out.println(app.lerPessoa());
    }

}
