/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.ifsc;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

import javax.sound.sampled.SourceDataLine;

public class App {

    public static void main(String[] args) {

        // Linha b = new Linha(new int[] { 10, 20 }, new int[] { 30, 20 }, 2, 3);

        // Scanner teclado = new Scanner(System.in);

        // int e = 0;

        // do {

        // System.out.println("Entre a espessura");
        // e = teclado.nextInt();

        // } while (e > Linha.ESPESSURA_MAX || e < Linha.ESPESSURA_MIN);// pegar o valor
        // da espessura máxima;

        // Linha a = new Linha(new int[] { 1, 2 }, new int[] { 3, 2 }, 1, 1);

        Pessoa juca = new Pessoa("Juca");

        Pessoa ana = new Pessoa("Ana");

        System.out.println(juca);
        // Deve imprimir: 1, juca;

        System.out.println(ana);
        // Deve imprimir: 2, ana;

        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> lista1 = new ArrayList<>();
        ArrayList<Pessoa> nomes = new ArrayList<>();

        // LinkedList<String> ll = new LinkedList<>();
        // LinkedList<Pessoa> ll1 = new LinkedList<>();

        lista1.add(juca);
        lista1.add(ana);

        lista.add("juca");
        lista.add("ana");

        // for (int i = 0; i < lista1.size(); i++) {
        // Pessoa p = lista1.get(i);
        // System.out.println(p);

        // }

        // for (Pessoa p : lista1) {
        // System.out.println(p);
        // }

        // lista.forEach(p -> System.out.println(p));

        // lista.forEach(System.out::println);

        // boolean b = nomes.contains("POO");

        System.out.println(lista1);

    }

}
