/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.ifsc;

public class App {

    private String nome = "POO";

    public void falar() {
        System.out.println("asdas" + this.nome);
    }

    public static void main(String[] args) {

        App b = new App();
        b.falar();

        // Buzz p = new Buzz(a.getNome());
    }
}
