services:
  database:
    container_name: mysql
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./env/.env-db
    restart: always
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: