/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ifsc.engtelecom;

import org.fusesource.jansi.AnsiConsole;
import static org.fusesource.jansi.Ansi.*;

// import barcode.CodigoDeBarra;

public class App {

    public static void main(String[] args) throws Exception {

        // System.out.println("olá mundo");

        // CodigoDeBarra.gerarCodigoDeBarra(23192319, "tuene.png");

        AnsiConsole.systemInstall();

        System.out.println(ansi().reset().eraseScreen().cursor(1, 1));

        AnsiConsole.systemUninstall();

        System.out.println(ansi().fgBlue().a("ola mundo!"));

    }
}
