/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Motor m1000 = new Motor(5000);
        Motor v8 = new Motor(9000);

        Carro fusca = new Carro(v8);

    }
}
