/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Contador aeromoca = new Contador(1.0);

        aeromoca.addValue();
        aeromoca.addValue();
        aeromoca.addValue();
        System.out.println(aeromoca);

        // Carro fusca = new Carro(100, "fusca");
        // Carro gol = new Carro(100, "gol");

        // System.out.println("fusca velocidade (inicial): " + fusca.obterVelocidade());
        // System.out.println("ferrari velocidade (inicial): " +
        // ferrari.obterVelocidade());

        // // System.out.println("fusca velocidade (inicial): " +
        // // fusca.getVelocidade());
        // // fusca.setVelocidade(100);
        // // System.out.println("fusca velocidade: " + fusca.getVelocidade());

        // System.out.println(fusca);

        // System.out.println(gol);

        // fusca.acelerar(99);
        // fusca.acelerar(99);
        // ferrari.acelerar(200);

        // fusca.velocidade = 100;

        // System.out.println("fusca velocidade: " + fusca.obterVelocidade());
        // System.out.println("ferrari velocidade: " + ferrari.obterVelocidade());
    }

}
