/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package engtelecom.poo;

import edu.princeton.cs.algs4.*;
import java.awt.*;

public class App {

    private Draw desenho;

    public App() {

        this.desenho = new Draw();
        this.desenho.setXscale(0, 800);
        this.desenho.setYscale(0, 800);
        this.desenho.enableDoubleBuffering();
    }

    public void desenhaGrade() {

        int fator = 200;

        int grade = (int) fator / 10;

        this.desenho.setPenColor(Draw.BLACK);
        for (int i = 0; i < 800; i += grade) {

            this.desenho.line(i, 0, i, 800);

        }

        for (int i = 0; i < 800; i += grade) {

            this.desenho.line(0, i, 800, i);
        }

    }

    public void desenhar() throws InterruptedException {

        Font font = this.desenho.getFont().deriveFont(30);
        this.desenho.setFont(font);

        Segment t = new Segment();
        for (int i = 0; i < 10000000; i++) {

            this.desenho.clear();

            this.desenhaGrade();

            t.desenhaTriangulo();
            // this.desenhaTriangulo();

            this.desenho.setPenColor(Draw.BLACK);
            this.desenho.text(400, 400, "" + i);
            this.desenho.show();

            Thread.sleep(50);

        }

    }

    // public void desenhaTriangulo() {

    // this.desenho.setPenColor(Draw.BLUE);

    // double[] coordenadaX = { 100, 400, 700 };
    // double[] coordenadaY = { 100, 700, 100 };

    // this.desenho.filledPolygon(coordenadaX, coordenadaY);
    // }

    public static void main(String[] args) throws InterruptedException {

        App app = new App();

        app.desenhar();
    }
}
