/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.ifsc;

public class App {
    
    Buzz buzz1 = new Buzz();
    Buzz buzz2 = new Buzz();
    Buzz buzz3 = new Buzz();

    Buzz.capaceteAberto();

    

}
